api_edificio_list:
    path: /api/edificios
    controller: App\Controller\Api\EdificioApiController::index
    methods: GET

api_edificio_show:
    path: /api/edificios/{id}
    controller: App\Controller\Api\EdificioApiController::show
    methods: GET

api_edificio_create:
    path: /api/edificios
    controller: 'App\Controller\Api\EdificioApiController::create'
    methods: ['POST']

api_edificio_delete:
    path: /api/edificios/{id}
    controller: 'App\Controller\Api\EdificioApiController::delete'
    methods: ['DELETE']


api_alumno_list:
    path: /api/alumnos
    controller: App\Controller\Api\AlumnoApiController::index
    methods: GET

api_alumno_show:
    path: /api/alumnos/{id}
    controller: App\Controller\Api\AlumnoApiController::show
    methods: GET

api_alumno_create:
    path: /api/alumnos
    controller: 'App\Controller\Api\AlumnoApiController::create'
    methods: ['POST']

api_alumno_delete:
    path: /api/alumnos/{id}
    controller: 'App\Controller\Api\AlumnoApiController::delete'
    methods: ['DELETE']

api_user_list:
    path: /api/users
    controller: 'App\Controller\Api\UserController::index'
    methods: ['GET']

api_user_show:
    path: /api/users/{id}
    controller: 'App\Controller\Api\UserController::show'
    methods: ['GET']

api_user_create:
    path: /api/users
    controller: App\Controller\Api\UserApiController::create
    methods: ['POST']

api_user_delete:
    path: /api/users/{id}
    controller: App\Controller\Api\UserApiController::delete
    methods: ['DELETE']

api_recurso_list:
    path: /api/recursos
    controller: App\Controller\Api\RecursoApiController::index
    methods: ['GET']

api_recurso_show:
    path: /api/recursos/{id}
    controller: App\Controller\Api\RecursoApiController::show
    methods: ['GET']

api_recurso_create:
    path: /api/recursos
    controller: App\Controller\Api\RecursoApiController::create
    methods: ['POST']

api_recurso_delete:
    path: /api/recursos/{id}
    controller: App\Controller\Api\RecursoApiController::delete
    methods: ['DELETE']

api_grupo_list:
    path: /api/grupos
    controller: App\Controller\Api\GrupoApiController::index
    methods: ['GET']

api_grupo_show:
    path: /api/grupos/{id}
    controller: App\Controller\Api\GrupoApiController::show
    methods: ['GET']

api_grupo_create:
    path: /api/grupos
    controller: App\Controller\Api\GrupoApiController::create
    methods: ['POST']

api_grupo_delete:
    path: /api/grupos/{id}
    controller: App\Controller\Api\GrupoApiController::delete
    methods: ['DELETE']

api_evento_list:
    path: /api/eventos
    controller: App\Controller\Api\EventoApiController::index
    methods: GET

api_evento_show:
    path: /api/eventos/{id}
    controller: App\Controller\Api\EventoApiController::show
    methods: GET

api_evento_create:
    path: /api/eventos
    controller: App\Controller\Api\EventoApiController::create
    methods: POST

api_evento_delete:
    path: /api/eventos/{id}
    controller: App\Controller\Api\EventoApiController::delete
    methods: DELETE

api_actividades_simple:
    path: /API/actividades/simple
    controller: App\Controller\Api\ActividadApiController::createSimple
    methods: [POST]
