controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
not_found:
    path: /error/not_found
    controller: App\Controller\CustomErrorController::notFound

# Ruta comodín para manejar todas las demás solicitudes
wildcard:
    path: /{any}
    controller: App\Controller\CustomErrorController::handleWildcard
    requirements:
        any: .*

